
language: r
r_github_packages: statnet/EpiModel@EpiModel_Overhaul_nwobjupdate
sudo: false
cache: packages

r:
  - release
  - devel

warnings_are_errors: true

notifications:
  email:
    on_success: never
    on_failure: change
