language: r
sudo: false
cache: packages

r:
  - release
  - devel

r_github_packages:
  statnet/EpiModel@EpiModel_Overhaul

warnings_are_errors: true

notifications:
  email:
    on_success: never
    on_failure: change
