
language: r
sudo: false
cache: packages

r_github_packages: 
- statnet/EpiModel
- chad-klumb/network@tergmLiteterms

warnings_are_errors: true

notifications:
  email:
    on_success: never
    on_failure: change
